config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end

  resources :movies do
        resources :reviews, only: [:new, :create]
      end
  resources :actors, only: [:index,:new, :edit,:create, :show]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
    has_many :staredins
    has_many :movies, through: :staredins

    validates :firstname,
              presence: true

    validates :lastname,
              presence: true

    def full_name
        "#{firstname} #{lastname}"
    end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]
  # before_action :load_movie, only: [:new, :create, :edit, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
    @staredin = Staredin.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    fields = actor_params
    @actor = Actor.new(fields[0])

    respond_to do |format|
      if @actor.save
        #update Staredin
        fields[1][:actor_id] = @actor.id
        @staredin = Staredin.new(fields[1])
        @staredin.save

        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    fields = actor_params
    respond_to do |format|
      if @actor.update(fields[0])
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected
  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      [params.require(:actor).permit(:firstname,:lastname),params.require(:staredin).permit(:movie_id,:date)]
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
  
end

app/views/actors/_form.html.erb
<%= form_for actor, :url => actors_path do |f| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <%= fields_for staredin do |u|%>
      <div class="field">
        <%= u.label :movie_id %>
        <%= #f.text_field :movie_id
        select("staredin", "movie_id", Movie.all.collect {|m| [ m.title, m.id ] }, {include_blank: 'None'}) %>
      </div>

      <div class="field">
        <%= u.label :date %>
        <%= u.datetime_select :date %>
      </div>

  <% end %>

  <div class="actions">
    <%= f.submit "Submit"%>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Actors</h1>

<table class="table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.firstname %></td>
        <td><%= actor.lastname %></td>
        <td><%= actor.movies[0].title %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor, staredin: @staredin %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @actor.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @actor.lastname %>
</p>

<p>
  <strong>Movies:</strong>
  <%= @actor.movies.each {|m| m.title} %>
</p>

<!-- <%= link_to 'Edit', actor_path(@actor) %> | -->
<%= link_to 'Back', actors_path %>