config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end

  resources :movies do
        resources :reviews, only: [:new, :create]
      end
  resources :actors, only: [:index,:new, :edit,:create, :show]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "#{@movie.title} was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
        params.require(:movie).permit(:title, :director, :runtime_in_minutes, :description, :poster_image_url, :release_date, :image)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
    def formatted_date(date)
        date.strftime('%b %d, %Y')
    end
end

app/views/movies/_form.html.erb
<div class="container">

    <%= form_for(movie, html: {multipart: true}) do |f| %>
    <% if movie.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(movie.errors.count, "error") %>
            prohibited this movie from being saved:</h2>

        <ul>
            <% movie.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class="field">
        <%= f.label :director %>
        <%= f.text_field :director %>
    </div>

    <div class="field">
        <%= f.label :runtime_in_minutes %>
        <%= f.number_field :runtime_in_minutes %>
    </div>

    <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <div class="field">
        <%= f.label :poster_image_url %>
        <%= f.text_field :poster_image_url %>
    </div>

    <div class="field">
        <%= f.label :release_date %>
        <%= f.datetime_select :release_date %>
    </div>

    <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
    <% end %>

</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Director</th>
      <th>Runtime in minutes</th>
      <th>Description</th>
      <th>Poster image url</th>
      <th>Release date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.order(:release_date).each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.director %></td>
        <td><%= movie.runtime_in_minutes %></td>
        <td><%= movie.description %></td>
        <td><%= image_tag(movie.poster_image_url,size: "54x82") %></td>
        <td><%= formatted_date(movie.release_date) %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Title:</strong>
    <%= @movie.title %>
</p>

<p>
    <strong>Director:</strong>
    <%= @movie.director %>
</p>

<p>
    <strong>Runtime in minutes:</strong>
    <%= @movie.runtime_in_minutes %>
</p>

<p>
    <strong>Description:</strong>
    <%= @movie.description %>
</p>

<p>
    <strong>Poster image url:</strong>
    <%= @movie.poster_image_url %>
</p>

<p>
    <strong>Release date:</strong>
    <%= formatted_date(@movie.release_date) %>
</p>

<h3>Actors staring in: <em><%= @movie.title %></em></h3>
<%@movie.actors.each do |actor| %>
  <p>
    <%=actor.full_name %>
  </p>
<%end%>
<p><%= link_to "Add an Actor", new_actor_path(@movie) %></p>
<h3>Reviews of
    <em><%= @movie.title %></em>: <%= @movie.review_average %>/10
</h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
    <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
    <p>Please
    <%= link_to "log in", new_session_path %>
    to see reviews and add your own.</p>
<% end %>
<%= link_to 'Edit', edit_movie_path(@movie) %>
<%= link_to 'Back to all movies', movies_path %>