config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end

  resources :movies do
        resources :reviews, only: [:new, :create]
      end
  resources :actors, only: [:index,:new, :edit,:create, :show]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :reviews

  def full_name
    "#{firstname} #{lastname}"
  end

  def admin?
    admin
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :destroy, :update]

    def new
        @user = User.new
    end

    def index
      if current_user.admin?
        @users = User.page(params[:page])
      else
        redirect_to movies_url
      end
    end

    def show
    end

    def edit
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_user_path, notice: 'Movie was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id # auto log in
            redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
        else
            render :new
        end
    end

    private
    def set_user
      @user = User.find(params[:id])
    end

    protected

    def user_params
        params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id # auto log in
            redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
        else
            render :new
        end
    end

    protected

    def user_params
        params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for @user, url: {action: "update"} do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %>
        prohibited this user from being saved:</h2>

    <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
</div>
<div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
</div>
<div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
</div>
<div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
</div>
<div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/admin/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', admin_user_path(@user) %> |

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Admin User Management</h1>

<table class="table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Admin?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email%></td>
        <td><%= user.admin%></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %>
        prohibited this user from being saved:</h2>

    <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
</div>
<div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
</div>
<div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
</div>
<div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
</div>
<div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/admin/users/show.html.erb
<div class="container">
    <div>
      <p> <strong>First Name:</strong>
          <%= @user.firstname %>
      </p>
    </div>
    <div>
      <p> <strong>Last Name:</strong>
          <%= @user.lastname %>
      </p>
    </div>
    <div>
      <p> <strong>Email:</strong>
          <%= @user.email %>
      </p>
    </div>
</div>
<%= link_to 'Edit', edit_admin_user_path(@user) %>
<%= link_to 'Back to all users', admin_users_path %>