config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end

  resources :movies do
        resources :reviews, only: [:new, :create]
      end
  resources :actors, only: [:index,:new, :edit,:create, :show]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
    <small>
        <% if current_user %>
        Signed in as
        <%= current_user.full_name %>
        <%= link_to "User Admin", admin_users_path if current_user.admin? %>
        (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
        <%= link_to "Log In", new_session_path %>
        |
        <%= link_to "Sign Up", new_user_path %>
        <% end %>
    </small>
</footer>

app/views/layouts/_header.html.erb
<header>
  <ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="/">Home</a></li>
    <li role="presentation"><a href="/actors">Actors</a></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RottenMangoes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
       <%= content_tag(:div, value) %>
     <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>